### ISSUE TITLE
不要把帳號密碼放在 source code

### ISSUE THREAD

**Issue by RammusXu** [Shyam-Chen/Backend-Starter-Kit#3]
https://github.com/Shyam-Chen/Backend-Starter-Kit/blob/master/tools/Dockerfile.prod

在 docker run 的時候可以把 env 帶入 docker container

Dockerfile 裡面不要填入敏感的資訊

**Comment by Shyam-Chen** [comment]
會加到 `.gitignore`

```bash
# 之前在使用 Gulp 或 Webpack 沒有辦法替換，現在不清楚
$ docker run --env-file=.env
```

https://github.com/Shyam-Chen/Vue-Fullstack-Starter#dockerization

**Comment by Shyam-Chen** [comment]
我將它放入 `backlog `

**Comment by Shyam-Chen** [comment]
#6 在 CircleCI 用參數動態設定環境變數就可以了，下一步用 https://github.com/circleci/encrypted-files
